name:                GRNPar
version:             0.1.0.0
github:              "wdas03/GRNPar"
license:             BSD3
author:              "William Das and Anushka Gupta"
maintainer:          "williamhdas@gmail.com"
copyright:           "William Das and Anushka Gupta"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wdas03/GRNpar#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- list-extras
- sbv
- vector
- bytestring
- graphviz
- graphite
- hashable
- text
- matrix
- word8
- parallel
- monad-par
- deepseq

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded
- -rtsopts
- -eventlog

library:
  source-dirs: src

executables:
  GRNPar-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -rtsopts
    - -eventlog
    - -O2
    - -fllvm

    dependencies:
    - GRNPar

tests:
  GRNPar-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GRNPar
